### ISSUE TITLE
Error when try use the code

### ISSUE THREAD

**Issue by paulocoutinhox** [EtienneDosSantos/stable-cascade-one-click-installer#13]
Hi,

Im getting this error:

```
python3 run-cascade.py 
/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Keyword arguments {'ignore_mismatched_sizes': True} are not expected by StableCascadePriorPipeline and will be ignored.
Loading pipeline components...:  33%|███████████████████████████████████████████████████████████▎                                                                                                                      | 2/6 [00:02<00:05,  1.35s/it]The config attributes {'c_in': 16} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.
/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/lora.py:384: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [01:13<00:00, 12.23s/it]
Loading pipeline components...:   0%|                                                                                                                                                                                          | 0/5 [00:00<?, ?it/s]The config attributes {'c_in': 4} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...:  20%|███████████████████████████████████▌                                                                                                                                              | 1/5 [00:00<00:02,  1.67it/s]
Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/python/ai-sd-test/run-cascade.py", line 22, in <module>
    decoder = StableCascadeDecoderPipeline.from_pretrained(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_utils.py", line 1263, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_utils.py", line 531, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/modeling_utils.py", line 669, in from_pretrained
    unexpected_keys = load_model_dict_into_meta(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/modeling_utils.py", line 154, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load /Users/paulo/.cache/huggingface/hub/models--stabilityai--stable-cascade/snapshots/f2a84281d6f8db3c757195dd0c9a38dbdea90bb4/decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
```

My code:

https://github.com/paulocoutinhox/ai-image-generator/blob/main/run-cascade.py

Can you help me?

Thanks.

**Comment by EtienneDosSantos** [comment]
The ValueError, caused by a shape mismatch, happens because the parameter name was changed from `c_in` to `in_channels` recently (inside kashif custom diffusers). However, both `StableCascadePriorPipeline` and `StableCascadeDecoderPipeline` continue to use the old parameter name `c_in` in their `config.json` files.

**Comment by EtienneDosSantos** [comment]
> I update and use your PR installing your repo, but the errors still:
> 
> ```
> python3 run-cascade.py                    
> /Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
>   torch.utils._pytree._register_pytree_node(
> Loading pipeline components...:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 4/6 [00:01<00:00,  2.91it/s]The config attributes {'c_in': 16} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.
> Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:21<00:00,  3.62s/it]
> Loading pipeline components...:  60%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                       | 3/5 [00:05<00:02,  1.44s/it]The config attributes {'c_in': 4} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.
> Loading pipeline components...:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 4/5 [00:10<00:02,  2.68s/it]
> Traceback (most recent call last):
>   File "/Users/paulo/Developer/workspaces/python/ai-sd-test/run-cascade.py", line 27, in <module>
>     decoder = StableCascadeDecoderPipeline.from_pretrained(
>   File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_utils.py", line 1263, in from_pretrained
>     loaded_sub_model = load_sub_model(
>   File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_utils.py", line 531, in load_sub_model
>     loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
>   File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/modeling_utils.py", line 669, in from_pretrained
>     unexpected_keys = load_model_dict_into_meta(
>   File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/modeling_utils.py", line 154, in load_model_dict_into_meta
>     raise ValueError(
> ValueError: Cannot load /Users/paulo/.cache/huggingface/hub/models--stabilityai--stable-cascade/snapshots/f2a84281d6f8db3c757195dd0c9a38dbdea90bb4/decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
> ```

Very strange it's not resolved. Perhaps a clean install would help? Also make sure to clear the `.cache`'s huggingface directory, just in case.

**Comment by paulocoutinhox** [comment]
Hi,

Yes, i execute a clean run and it download everything again:

```bash
rm -rf ~/.cache/huggingface
             
python3 run-cascade.py 
              
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
model_index.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 599/599 [00:00<00:00, 138kB/s]
text_encoder/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 639/639 [00:00<00:00, 391kB/s]
prior/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 777/777 [00:00<00:00, 746kB/s]
image_encoder/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 584/584 [00:00<00:00, 2.82MB/s]
scheduler/scheduler_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 117/117 [00:00<00:00, 183kB/s]
(…)ature_extractor/preprocessor_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 466/466 [00:00<00:00, 3.02MB/s]
tokenizer/tokenizer_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 705/705 [00:00<00:00, 190kB/s]
tokenizer/special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 588/588 [00:00<00:00, 1.22MB/s]
tokenizer/merges.txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 827kB/s]
tokenizer/vocab.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 862k/862k [00:01<00:00, 708kB/s]
tokenizer/tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.22M/2.22M [00:02<00:00, 910kB/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 608M/608M [01:35<00:00, 6.38MB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.39G/1.39G [02:18<00:00, 10.0MB/s]
diffusion_pytorch_model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.18G/7.18G [06:04<00:00, 19.7MB/s]
Fetching 14 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [06:05<00:00, 26.09s/it]
Loading pipeline components...:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 4/6 [00:04<00:02,  1.08s/it]The config attributes {'c_in': 16} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:27<00:00,  4.65s/it]
model_index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 493/493 [00:00<00:00, 68.4kB/s]
scheduler/scheduler_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 117/117 [00:00<00:00, 38.7kB/s]
decoder/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 885/885 [00:00<00:00, 2.41MB/s]
tokenizer/special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 588/588 [00:00<00:00, 2.66MB/s]
text_encoder/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 633/633 [00:00<00:00, 1.64MB/s]
tokenizer/merges.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 2.08MB/s]
vqgan/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 329/329 [00:00<00:00, 255kB/s]
tokenizer/tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 705/705 [00:00<00:00, 1.69MB/s]
tokenizer/vocab.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 862k/862k [00:01<00:00, 660kB/s]
tokenizer/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.22M/2.22M [00:01<00:00, 1.25MB/s]
diffusion_pytorch_model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.8M/36.8M [00:06<00:00, 6.09MB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.39G/1.39G [01:35<00:00, 14.5MB/s]
diffusion_pytorch_model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.13G/3.13G [02:52<00:00, 18.1MB/s]
Fetching 13 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [02:52<00:00, 13.31s/it]
Loading pipeline components...:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 4/5 [00:03<00:00,  1.32it/s]The config attributes {'c_in': 4} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.                                                | 1.13G/3.13G [01:35<02:53, 11.5MB/s]
Loading pipeline components...:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 4/5 [00:07<00:01,  1.83s/it]
Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/python/ai-sd-test/run-cascade.py", line 27, in <module>
    decoder = StableCascadeDecoderPipeline.from_pretrained(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_utils.py", line 1263, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_utils.py", line 531, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/modeling_utils.py", line 669, in from_pretrained
    unexpected_keys = load_model_dict_into_meta(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/modeling_utils.py", line 154, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load /Users/paulo/.cache/huggingface/hub/models--stabilityai--stable-cascade/snapshots/f2a84281d6f8db3c757195dd0c9a38dbdea90bb4/decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
```

I tried update all requirements, inclusive your branch only to check if it can be the problem, but same problem:

```bash
python3 -m pip install -r requirements.txt -U

Defaulting to user installation because normal site-packages is not writeable
Collecting diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3 (from -r requirements.txt (line 2))
  Cloning https://github.com/EtienneDosSantos/diffusers.git (to revision wuerstchen-v3) to /private/var/folders/dl/21rxvhwn3zq8vjw5kc_9py380000gn/T/pip-install-km4z4coj/diffusers_909fc981e4334110825e5beb08b10640
  Running command git clone --filter=blob:none --quiet https://github.com/EtienneDosSantos/diffusers.git /private/var/folders/dl/21rxvhwn3zq8vjw5kc_9py380000gn/T/pip-install-km4z4coj/diffusers_909fc981e4334110825e5beb08b10640
  Running command git checkout -b wuerstchen-v3 --track origin/wuerstchen-v3
  Switched to a new branch 'wuerstchen-v3'
  branch 'wuerstchen-v3' set up to track 'origin/wuerstchen-v3'.
  Resolved https://github.com/EtienneDosSantos/diffusers.git to commit a9b3952c20985939fa094b4ae9e73a96e99e2537
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: accelerate in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 3)) (0.27.2)
Requirement already satisfied: transformers in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 4)) (4.37.2)
Requirement already satisfied: peft in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from -r requirements.txt (line 5)) (0.8.2)
Requirement already satisfied: filelock in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from torch->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from torch->-r requirements.txt (line 1)) (4.9.0)
Requirement already satisfied: sympy in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from torch->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from torch->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from torch->-r requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: fsspec in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from torch->-r requirements.txt (line 1)) (2024.2.0)
Requirement already satisfied: importlib-metadata in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (7.0.1)
Requirement already satisfied: huggingface-hub>=0.20.2 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (0.20.3)
Requirement already satisfied: numpy in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (2023.12.25)
Requirement already satisfied: requests in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: safetensors>=0.3.1 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (0.4.2)
Requirement already satisfied: Pillow in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (10.2.0)
Requirement already satisfied: packaging>=20.0 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from accelerate->-r requirements.txt (line 3)) (23.2)
Requirement already satisfied: psutil in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from accelerate->-r requirements.txt (line 3)) (5.9.8)
Requirement already satisfied: pyyaml in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from accelerate->-r requirements.txt (line 3)) (6.0.1)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from transformers->-r requirements.txt (line 4)) (0.15.2)
Requirement already satisfied: tqdm>=4.27 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from transformers->-r requirements.txt (line 4)) (4.66.1)
Requirement already satisfied: zipp>=0.5 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from importlib-metadata->diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from jinja2->torch->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from requests->diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from requests->diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from requests->diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from requests->diffusers@ git+https://github.com/EtienneDosSantos/diffusers.git@wuerstchen-v3->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in /Users/paulo/Library/Python/3.9/lib/python/site-packages (from sympy->torch->-r requirements.txt (line 1)) (1.3.0)
```

and executed again:

```bash
python3 run-cascade.py                       
/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Loading pipeline components...:   0%|                                                                                                                                                                                          | 0/6 [00:00<?, ?it/s]The config attributes {'c_in': 16} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:25<00:00,  4.32s/it]
Loading pipeline components...:  40%|███████████████████████████████████████████████████████████████████████▏                                                                                                          | 2/5 [00:04<00:06,  2.01s/it]The config attributes {'c_in': 4} were passed to StableCascadeUnet, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...:  40%|███████████████████████████████████████████████████████████████████████▏                                                                                                          | 2/5 [00:09<00:13,  4.64s/it]
Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/python/ai-sd-test/run-cascade.py", line 27, in <module>
    decoder = StableCascadeDecoderPipeline.from_pretrained(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_utils.py", line 1263, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_utils.py", line 531, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/modeling_utils.py", line 669, in from_pretrained
    unexpected_keys = load_model_dict_into_meta(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/diffusers/models/modeling_utils.py", line 154, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load /Users/paulo/.cache/huggingface/hub/models--stabilityai--stable-cascade/snapshots/f2a84281d6f8db3c757195dd0c9a38dbdea90bb4/decoder because embedding.1.weight expected shape tensor(..., device='meta', size=(320, 64, 1, 1)), but got torch.Size([320, 16, 1, 1]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
```

Same problem.

Im on M1 machine.
