### ISSUE TITLE
Mac M1 Trackback (most recent call last): errors on ./run.sh file

### ISSUE THREAD

**Issue by SayBeep** [EtienneDosSantos/stable-cascade-one-click-installer#21]
after running "run.sh" i get the localhost page then it exits.
the terminal has the following errors.
Mac M1, python 3.10.9 
-----------------------------------------------{
 stable-cascade-one-click-installer-main % ./run.sh
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_sync/http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/.pyenv/versions/3.10.9/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stable-cascade-one-click-installer-main/run.py", line 360, in <module>
    demo.launch(inbrowser=True)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2039, in launch
    httpx.get(f"{self.local_url}startup-events", verify=ssl_verify)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_api.py", line 198, in get
    return request(
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/Users/.pyenv/versions/3.10.9/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/stable-cascade-one-click-installer-main/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out
Mac-mini stable-cascade-one-click-installer-main % 
}

**Comment by EtienneDosSantos** [comment]
Hmm, not sure what causes this behaviour. Perhaps it is caused by the macOS firewall interfering? You could temporarily disable the firewall to test.

**Comment by SayBeep** [comment]
after restarting with fire wall disabled, the same error has occurred.
I'll try a different global python version see if I get different errors.

**Comment by EtienneDosSantos** [comment]
> I'll try a different global python version see if I get different errors.

I'm using Python 3.10.9, if you want to try that.
