### ISSUE TITLE
New update hugingface and error 

### ISSUE THREAD

**Issue by XT-404** [EtienneDosSantos/stable-cascade-one-click-installer#28]
Good morning
when launching the code, an update is installed from hugingface and crashes the code

Loading pipeline components...:  33%|█████████████████                                  | 2/6 [00:00<00:00, 399.97it/s]
Traceback (most recent call last):
  File "X:\stable-cascade-one-click-installer-main\Code_Example-v0.0.31.py", line 18, in <module>
    prior = StableCascadePriorPipeline.from_pretrained("stabilityai/stable-cascade-prior", torch_dtype=dtype).to(device)
  File "X:\stable-cascade-one-click-installer-main\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "X:\stable-cascade-one-click-installer-main\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1263, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "X:\stable-cascade-one-click-installer-main\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 443, in load_sub_model
    class_obj, class_candidates = get_class_obj_and_candidates(
  File "X:\stable-cascade-one-click-installer-main\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 347, in get_class_obj_and_candidates
    class_obj = getattr(library, class_name)
  File "X:\stable-cascade-one-click-installer-main\venv\lib\site-packages\diffusers\utils\import_utils.py", line 697, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module diffusers has no attribute StableCascadeUNet
Appuyez sur une touche pour continuer...

**Comment by EtienneDosSantos** [comment]
**Good morning!**

The error you're encountering is likely due to recent updates in the Hugging Face repository where the Stable Cascade models are hosted. It seems like you might be using an older version of the one-click-installer.

**Here's how to fix it:**

1. **Delete and reinstall:**  
   - Delete your existing `stable-cascade-one-click-installer` directory.
   - Download and reinstall a fresh copy. This should resolve the issue.

**Alternative: Reinstall using git:**

1. **Open a command prompt (cmd.exe).**
2. **Navigate to your desired installation directory:**
   - Use the `cd FolderName` command to change directories. 
3. **Clone the repository:**
   -  `git clone https://github.com/EtienneDosSantos/stable-cascade-one-click-installer`
4. **Run the installer:**
   - Double-click the `install.bat` file.

**Advantage of the git method:** You can easily update the installer in the future by running `update.bat` (which executes a `git pull`).

**Let me know if this works for you!**

**Comment by XT-404** [comment]
@EtienneDosSantos 
Okay, I will make this happen, thank you very much for your quick response and detailed explanation :)
