### ISSUE TITLE
Timeouts and No HIP GPU errors

### ISSUE THREAD

**Issue by thomasmcgannon** [EtienneDosSantos/stable-cascade-one-click-installer#29]
Hello,
I just followed the instructions to install this on Linux Mint, I have an Nvidia 4060ti, so I would expect this should work.

I got through the installation fine, and was able to run the UI and download all the hugging face models, however as soon as I load the UI I get a bunch of timeout errors

```
Gtk-Message: 18:51:00.875: Failed to load module "xapp-gtk3-module"
Opening in existing browser session.
Exception in thread Thread-3 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/analytics.py", line 61, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/analytics.py", line 117, in get_local_ip_address
    ip_address = httpx.get(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_api.py", line 198, in get
    return request(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out
Exception in thread Thread-5 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/analytics.py", line 61, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/analytics.py", line 117, in get_local_ip_address
    ip_address = httpx.get(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_api.py", line 198, in get
    return request(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out
```
Then when I try and generate an image I get this HID error

```
Processed prompt: cat in hat
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  8.23it/s]
Traceback (most recent call last):
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1695, in process_api
    result = await self.call_function(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1235, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/gradio/utils.py", line 692, in wrapper
    response = f(*args, **kwargs)
  File "/ai/stable-cascade-one-click-installer/run.py", line 62, in generate_images
    prior = load_model("prior")
  File "/ai/stable-cascade-one-click-installer/run.py", line 25, in load_model
    model = StableCascadePriorPipeline.from_pretrained("stabilityai/stable-cascade-prior", variant="bf16", torch_dtype=dtype).to(device)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 418, in to
    module.to(device, dtype)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/ai/stable-cascade-one-click-installer/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
```
Do you have any idea what could be causing this? Do I need to pass any parameters so that it can detect the GPU?

**Comment by EtienneDosSantos** [comment]
Indeed, this is quite unexpected. 🤔 Could you please double-check that your GPU drivers are fully up to date? I’ll take another look at the scripts in codespace to determine if the issue might be related.

**Comment by thomasmcgannon** [comment]
I have the latest drivers available on Linux Mint 21.3 with Nvidia driver 545.29.06, and it has been working fine with a1111, comfyUI and Forge, so I'm curious what might be different here :sweat_smile: 

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     Off | 00000000:01:00.0  On |                  N/A |
|  0%   42C    P8              12W / 165W |   3003MiB / 16380MiB |      7%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by EtienneDosSantos** [comment]
Sadly, I couldn't determine the cause of this behavior. I retested the scripts and launched the GUI, but the models exceeded GitHub Codespaces capacity, making it impossible to reproduce the errors.

**Comment by thomasmcgannon** [comment]
So I found the solution to both problems..

The timeouts was somehow related to Gradio analytics, when I passed the analytics_enabled=False flag that issue went away. Internally it's trying to access checkip.amazonaws.com and for some reason it timesout for me, I suspect it may be something to do with DNS proxies I'm using for region unlocking, but regardless, this fixed it :)

`with gr.Blocks(theme=gr.themes.Soft(), analytics_enabled=False) as demo: # Change to your desired theme`

The GPU issue was because pip was installing the rocm versions of torch and torchvision, the only way I was able to overcome this was by hardcoding some version:

```
torch==2.2.1+cu121
torchvision==0.17.1+cu121
```

I'm happy to say I now have a photo of a very cute cat in a hat!

**Comment by EtienneDosSantos** [comment]
Weird how it defaulted to the rocm version even with cuda specified in requirements.txt. I'll definitely update requirements.txt to use `torch==2.2.1+cu121` and `torchvision==0.17.1+cu121` to prevent this in the future. That's the version it's installing on my windows machine with the current requirements anyway.

Also, good point about the analytics-enabled flag. Can't hurt to add that in. Thanks a ton for the help!
