### ISSUE TITLE
Error two Generation picture: 

### ISSUE THREAD

**Issue by XT-404** [EtienneDosSantos/stable-cascade-one-click-installer#37]
Hello dear developer:
I would like to contact you. I carried out the update which logically corrects the anomaly in multiple image generation, and it still does not work.
if I go beyond 1 to 2, I get the following error:

```
Traceback (most recent call last):
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\gradio\route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\gradio\blocks.py", line 1695, in process_api
    result = await self.call_function(
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\gradio\blocks.py", line 1235, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\gradio\utils.py", line 692, in wrapper
    response = f(*args, **kwargs)
  File "X:\Oneclick\stable-cascade-one-click-installer\run.py", line 86, in generate_images
    decoder_output = decoder(
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\Oneclick\stable-cascade-one-click-installer\venv\lib\site-packages\diffusers\pipelines\stable_cascade\pipeline_stable_cascade.py", line 405, in __call__
    torch.cat([prompt_embeds_pooled, negative_prompt_embeds_pooled])
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 1280 but got size 640 for tensor number 1 in the list.
```

thank you for your analysis
NOT: my graphics card and a 4090 24GO special Edition

**Comment by EtienneDosSantos** [comment]
I'm sorry it took so long for me to answer.

Have you tried a clean install?

**Comment by XT-404** [comment]
@EtienneDosSantos 
Hello dear developer, no worries. Indeed, before contacting you, I applied the following technique: when in doubt, reinstall everything and test. Despite four complete reinstalls in various directories, if I launch more than two images, I encounter the indicated errors.

**Comment by XT-404** [comment]
(venv) X:\Oneclick\stable-cascade-one-click-installer>pip show diffusers
Name: diffusers
Version: 0.27.0
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)
Author-email: patrick@huggingface.co
License: Apache 2.0 License
Location: x:\oneclick\stable-cascade-one-click-installer\venv\lib\site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by:

**Comment by EtienneDosSantos** [comment]
Great, I think we've found the culprit to the issue! 😊

**Possible solution to the issue:**

1. **Open a terminal in your "stable-cascade-one-click-installer" folder:**
   - Right-click the folder.
   - Select "Open in terminal".

2. **Activate the virtual environment and update diffusers:**
   ```bash
   venv\Scripts\activate
   pip install diffusers==0.27.2

**Comment by XT-404** [comment]
@EtienneDosSantos 

thank you, I applied your recommendation, everything works now :), you and a chef, thank you very much
